package content;

public enum TokenType {
    USING, NAMESPACE,
    CLASS, STRUCT, INTERFACE, ENUM, PUBLIC, PRIVATE, STATIC, FINAL, ABSTRACT, OPERATOR, GET, SET,
    IF, ELSE, FOR, WHILE, DO, SWITCH, CASE, LOCK,
    BREAK, CONTINUE, RETURN, VAR, NEW, THIS, SUPER, DEFAULT,
    SEMICOLON, COLON, DOT, QUEST, LAMBDA,
    ADD, SUB, MUL, DIV, MOD, RSHIFT, LSHIFT, INC, DEC, SETVAL,
    SETADD, SETSUB, SETDIV, SETMOD, SETRSHIFT, SETLSHIFT,
    BITAND, BITOR, BITNOT, BITXOR,
    SETAND, SETOR, SETNOT, SETXOR,
    EQUAL, MORE, LESS, EMORE, ELESS, DIF, AND, OR, NOT,

    CLASSNAME, NAME, NUMBER, TRUE, FALSE, NULL,

    BRACE, BRACKET, PAREN, TAG, QUOT, DQUOT
}
